num = int(input('Digite um número de 0 a 9999: '))
numlock = str(num)
print('Thousand: {}'.format(numlock[-4:-3]))
print('hundred: {}'.format(numlock[-3:-2]))
print('Dozens: {}'.format(numlock[-2:-1]))
print('Unity: {}'.format(numlock[-1]))
