import coin
print('-'*45)
money = float(input('Enter the price: R$'))
print('-'*45)
print(f'The half of {coin.coin(money)} is {coin.coin(coin.half(money))}.')
print(f'The double of {coin.coin(money)} is {coin.coin(coin.double(money))}.')
print(f'Increasing 10% of {coin.coin(money)}, we have {coin.coin(coin.increase(money, 10))}.')
print(f'Decreasing 10% of {coin.coin(money)}, we have {coin.coin(coin.decrease(money, 10))}.')
print('-'*45)
print(' '*20, 'END')
print('-'*45)