x = input('Type something: ')
print('Is numeric: {}'.format(x.isnumeric()))
print('Is alphanumeric: {}'.format(x.isalnum()))
print('Is ascii: {}'.format(x.isascii()))
print('Is decimal: {}'.format(x.isdecimal()))
print('Is dígit: {}'.format(x.isdigit()))
print('Is identifiable: {}'.format(x.isidentifier()))
print('Has only lowercases: {}'.format(x.islower()))
print('Has only uppercases: {}'.format(x.isupper()))
print('Is printable: {}'.format(x.isprintable()))
print('Has only spaces: {}'.format(x.isspace()))
print('Is capitalized: {}'.format(x.istitle()))
